version: '3.3'
services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=products
      - DB_USER=user2
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=user2
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=products
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local